In [50]:
import os
import rasterio as rio
import numpy as np
import json
import webbrowser
import requests
import utils 
import pandas as pd

In [51]:
path = "./rasterImages/NDVI.tif"
raster = rio.open(path)


In [52]:
ip = 'localhost'
port = '8080'
direction = 'Escairon rua doutor jose portela 4'
api_url = 'http://{}:{}/search?q={}'.format(ip,port,direction)
api_url

'http://localhost:8080/search?q=Escairon rua doutor jose portela 4'

In [53]:
coords = utils.send_request(api_url)
coords

(-7.6393883, 42.5859087)

In [54]:
a = utils.getNDVI(coords[0],coords[1],raster,3)
a["values"]


array([0.39703596, 0.4023825 , 0.40783772, 0.4098348 , 0.3959255 ,
       0.40715486, 0.38138646, 0.38001165, 0.38052472, 0.4115192 ,
       0.40880212, 0.3838174 , 0.3753197 , 0.38098827, 0.41285402,
       0.40927932, 0.37752518, 0.37500095, 0.39364278, 0.4119322 ,
       0.42005306, 0.38171366, 0.3947283 , 0.41590464, 0.40824443],
      dtype=float32)

In [73]:
direcciones = pd.read_table("direcciones_galicia.txt",sep=",",header=None)
pixels_ndvi = []

for i in range(len(direcciones)):
    api_url = 'http://{}:{}/search?q={}'.format(ip,port,direcciones.iloc[i,0])
    coords = utils.send_request(api_url)
    pixels_ndvi.append(utils.getNDVI(coords[0],coords[1],raster,3)['values'])

In [76]:

pixels_ndvi

[array([0.48772076, 0.48689362, 0.41953105, 0.44467804, 0.5180267 ,
        0.46502328, 0.49382707, 0.47280866, 0.44868183, 0.51427734,
        0.4644546 , 0.49378434, 0.47996038, 0.41995126, 0.5165511 ,
        0.47229052, 0.49766293, 0.4700944 , 0.4113829 , 0.47019237,
        0.43689018, 0.4705325 , 0.48041   , 0.40445498, 0.45308164],
       dtype=float32),
 array([-0.1372078 , -0.13932581, -0.14353856, -0.139844  , -0.13950068,
        -0.13694067, -0.13971639, -0.13943996, -0.13825317, -0.13809952,
        -0.13691463, -0.13943693, -0.13918364, -0.13587502, -0.13734744,
        -0.13563693, -0.14162016, -0.14228885, -0.14391108, -0.1374354 ,
        -0.13662444, -0.14106575, -0.14285612, -0.14131628, -0.137648  ],
       dtype=float32),
 array([0.41777703, 0.4367113 , 0.44469982, 0.45672995, 0.47194842,
        0.41104734, 0.44195303, 0.46129417, 0.4591369 , 0.47528595,
        0.40187395, 0.43290976, 0.45179972, 0.4604458 , 0.47449297,
        0.3449197 , 0.4033627 , 0.43380195,